### ISSUE TITLE
Liquid-dsp fails to install

### ISSUE THREAD

**Issue by bentech** [dholm/homebrew-sdr#1]
brew install liquid-dsp --HEAD -v
==> Installing liquid-dsp from dholm/homebrew-sdr
==> Cloning https://github.com/jgaeddert/liquid-dsp.git
git --git-dir /Library/Caches/Homebrew/liquid-dsp--git/.git status -s
Updating /Library/Caches/Homebrew/liquid-dsp--git
git config remote.origin.url https://github.com/jgaeddert/liquid-dsp.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 39dd78f firfilt: adding cccf example to demonstrate cross-correlation
==> Checking out branch master
git checkout-index -a -f --prefix=/private/tmp/liquid-dsp-8AyQPs/
==> ./bootstrap.sh
aclocal: error: aclocal: file '/usr/local/share/aclocal/freetype2.m4' does not exist
==> ./configure --prefix=/usr/local/Cellar/liquid-dsp/HEAD
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for a sed that does not truncate output... /usr/local/Library/ENV/4.3/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking for error_at_line... no
checking how to run the C preprocessor... clang -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for main in -lc... yes
checking for main in -lm... yes
checking for malloc... yes
checking for realloc... yes
checking for free... yes
checking for memset... yes
checking for memmove... yes
checking for sinf... yes
checking for cosf... yes
checking for expf... yes
checking for cargf... yes
checking for cexpf... yes
checking for crealf... yes
checking for cimagf... yes
checking for sqrtf... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking complex.h usability... yes
checking complex.h presence... yes
checking for complex.h... yes
checking for string.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking fec.h usability... no
checking fec.h presence... no
checking for fec.h... no
checking fftw3.h usability... yes
checking fftw3.h presence... yes
checking for fftw3.h... yes
checking for fftwf_plan_dft_1d in -lfftw3f... yes
checking for create_viterbi27 in -lfec... no
configure: WARNING: fec library useful but not required
checking for inline... inline
checking for size_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking size of int... 4
checking size of unsigned int... 4
./configure: line 4559: syntax error near unexpected token `no,,'
./configure: line 4559:`AX_GCC_ARCHFLAG(no,,)'
==> Formula
Tap: dholm/homebrew-sdr
Path: /usr/local/Library/Taps/dholm/homebrew-sdr/liquid-dsp.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 5b855d60d099e4e0cd342c7d3bb9a78e5cdbc8fb
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10.3-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.6 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/ben1/.rvm/rubies/ruby-2.1.1/bin/ruby
Java: 1.8.0-ea
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/fftw/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/fftw/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/pkg-config/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: liquid-dsp HEAD did not build
Logs:
     /Users/ben1/Library/Logs/Homebrew/liquid-dsp/01.bootstrap.sh
     /Users/ben1/Library/Logs/Homebrew/liquid-dsp/02.configure
     /Users/ben1/Library/Logs/Homebrew/liquid-dsp/02.configure.cc
     /Users/ben1/Library/Logs/Homebrew/liquid-dsp/config.log

**Comment by dholm** [comment]
`aclocal: error: aclocal: file '/usr/local/share/aclocal/freetype2.m4' does not exist`

Do you have `/usr/local/share/aclocal/freetype2.m4` and does it point to an existing file?  If you have the link but not the file try removing the link.  FreeType is not a dependency of `liquid-dsp` but it looks like it is causing `aclocal` to fail.
