### ISSUE TITLE
pothos.rb -- the upstream branch now builds on OSX

### ISSUE THREAD

**Issue by guruofquality** [dholm/homebrew-sdr#10]
Just a heads up that Pothos should build on OSX just fine now, so the patches aren't needed. Here is the relevant discussion:  https://groups.google.com/forum/#!topic/pothos-users/Z2R_kBDjnXg

**Comment by guruofquality** [comment]
FYI -- I now have a formal homebrew tap for pothos, soapysdr, support modules, and toolkits: https://github.com/pothosware/homebrew-pothos/wiki

**Comment by dholm** [comment]
@guruofquality Thank you, I've removed the patches and fixed the formula.  I'll check your formulas out and link to your Homebrew tap instead.

**Comment by dholm** [comment]
@guruofquality Added link in my `README.md` and removed the formula.  Closing this issue now.
