### ISSUE TITLE
error installing libosmocore OS X 10.11

### ISSUE THREAD

**Issue by nejohnson2** [dholm/homebrew-sdr#13]
I just updated my system and am trying to install libosmocore but keep getting [this error](https://gist.github.com/8555f71d950280268a57).  I did have to install an older version of cmake to build gnuradio properly ([see this issue](https://github.com/Homebrew/homebrew/issues/46000)) but not sure what the deal is... any ideas?

**Comment by dholm** [comment]
@nejohnson2 Should be fixed now.

**Comment by dholm** [comment]
Closing this issue now.  Please reopen if it happens again.
