### ISSUE TITLE
Calling 'depends_on ... => :python' is deprecated

### ISSUE THREAD

**Issue by muellermartin** [dholm/homebrew-sdr#28]
The formula for `gr-osmosdr` uses now deprecated syntax for a dependency. This causes `brew update` and similar commands to output a verbose warning:

```
Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr/gr-osmosdr.rb:9:in `<class:GrOsmosdr>'
Please report this to the dholm/sdr tap!
```

This issue might also be related to #26.

**Comment by dholm** [comment]
Should be fixed now, thanks for reporting it.
