### ISSUE TITLE
Missing cmake depends_on for gr-osmosdr

### ISSUE THREAD

**Issue by grutz** [dholm/homebrew-sdr#30]
In the last change for `gr-osmosdr.rb` it appears the cmake build line has been removed by accident:

`  depends_on "cmake" => :build`  

https://github.com/dholm/homebrew-sdr/commit/1230db240194cb7be1b83b6b00ea126a0117772a#diff-83bafb2f34730b11322fc1c86a7b9081L7

**Comment by dholm** [comment]
Oops, thanks!
