### ISSUE TITLE
depends_on :fortran depreciated

### ISSUE THREAD

**Issue by nickrose** [dholm/homebrew-sdr#31]
home-brew gave me a warning and said I should report it to the repository maintainer:

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr/gr-specest.rb:7:in `<class:GrSpecest>'
Please report this to the dholm/sdr tap!

**Comment by talesluna** [comment]
Same issue here.

Temporally i forked the project to solve this: https://github.com/talesluna/homebrew-sdr
if all run fine i will send a new pull request

**Comment by tc2290** [comment]
@talesluna 

Getting the following error when trying to tap your fork. Any ideas?

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/talesluna/homebrew-sdr/gnuradio.rb
undefined method `sha1' for #<Class:0x000001018d2b40>
Error: Cannot tap talesluna/sdr: invalid syntax in tap!
