### ISSUE TITLE
Invalid formula prevents tap

### ISSUE THREAD

**Issue by nrcharles** [dholm/homebrew-sdr#39]
==> Tapping dholm/sdr
Cloning into '/usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 434 (delta 0), reused 1 (delta 0), pack-reused 430
Receiving objects: 100% (434/434), 119.61 KiB | 1.81 MiB/s, done.
Resolving deltas: 100% (264/264), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr/liquid-dsp.rb
invalid attribute for formula 'dholm/sdr/liquid-dsp': version (nil)
Error: Cannot tap dholm/sdr: invalid syntax in tap!

**Comment by bibanul** [comment]
any chance when this will be merged? thx

**Comment by zenoamaro** [comment]
I'm working around this by brewing from @linkslice's tap:

```
brew install linkslice/sdr/...
```

**Comment by linkslice** [comment]
> I'm working around this by brewing from @linkslice's tap:
> 
> ```
> brew install linkslice/sdr/...
> ```

yup, that's what I've been doing, too! :-D
