### ISSUE TITLE
liquid-dsp doesn't build

### ISSUE THREAD

**Issue by gloob** [dholm/homebrew-sdr#4]
https://gist.github.com/anonymous/60768bc813284943be5c

Seems there's a problem with the stable version of liquid-dsp, we need to do a ./reconf if its stable.

**Comment by dholm** [comment]
@gloob I just pushed a fix for building `liquid-dsp` 1.2.0.  Please try it again.

**Comment by gloob** [comment]
Just tested it, it works perfectly in OS X El Capitan (10.11 (15A284)).

Thanks @dholm !
