### ISSUE TITLE
rtl-sdr already in main homebrew.

### ISSUE THREAD

**Issue by stahlfabrik** [dholm/homebrew-sdr#8]
Hi,

the rtl-sdr is imho already in main homebrew under the name "librtlsdr".

Is there a reason to keep and use a local "dupe" for the main version? Maybe you could get your changes merged into there...

Regards!

**Comment by dholm** [comment]
Mine is based on an unofficial fork that offers some additional features, such as an improved frequency range.  Since it is unofficial I don't think Homebrew would accept changing the official formula.
